spring:
  application:
    name: SWIFT
  datasource:
    url: jdbc:postgresql://localhost:5432/swift_code
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: haslo1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        ddl-auto: update


